name: Test/Lint/Release

permissions:
  contents: write

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test-lint:
    if: ${{ !startsWith(github.event.head_commit.message, 'tag') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 18

      - run: pnpm i
      - run: docker run -p 3000:3000 -d --name signway --rm gabotechs/signway my-id my-secret
      - run: pnpm build
      - run: pnpm test
      - run: pnpm lint
      - run: docker kill signway

  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - unit-test-lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0' # https://github.com/actions/checkout/issues/217

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 18

      - name: Tag
        id: tag
        run: |
          version=$(.github/semver.sh)
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          // TODO
          git add .
          git commit -m "tag: v$version"
          git tag "v$version"
          git push
          git push --tags
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Release
        run: gh release create "v${{ steps.tag.outputs.version }}"
        env:
          GH_TOKEN: ${{ github.token }}

      - run: pnpm build
      - run: pnpm publish
